### ISSUE TITLE
ScriptURI parameter has different values for the name within the project

### ISSUE THREAD

**Issue by techtalk722** [Azure/AVDBlueprint#120]
The ScriptURI parameter is being referenced by the Mgmtvm artifact but the parameter in the Blueprint.json file is "_ScriptURI".  This causes an error when attempting to publish the blueprint.  Removing the underscore( _ ) in front of the parameter value fixes the issue.

**Comment by techtalk722** [comment]
The assign_default.json also uses the "_ScriptURI" value.

**Comment by robsmi-msfte** [comment]
Hello @techtalk722,

I believe that was fixed earlier, or in the pull requests from today.  I checked the repo and it no longer references "_ScriptURI", but the updated name of "ScriptURI".  I will close this issue, but if you find a problem please open a new issue.

Thanks,

Robert Smith
