### ISSUE TITLE
Keyvault error : The vault name 'AVDBP01-sharedsvcs-kv' is already in use

### ISSUE THREAD

**Issue by jlou07** [Azure/AVDBlueprint#128]
Hi Team,

Another error during my Blueprint deployment : 

The artifact 'keyvault' of type 'Template' failed to deploy due to the following error: Template deployment failed with error [ { "code": "VaultAlreadyExists", "message": "The vault name 'AVDBP01-sharedsvcs-kv' is already in use. Vault names are globaly unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information on soft delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740." } ]

Therefore I modified the Resource Prefix “AVDBP01” by “AVDBP01jlo” and the key vault was created correclty, but I still get the same error message. Why ?

![keyvault](https://user-images.githubusercontent.com/58774660/135842711-fa71e4fe-af98-4d6d-a774-5c9ea8c59a51.png)

Thanks,

Jean-Loup

**Comment by robsmi-msfte** [comment]
Hello @jlou07,

Try checking your deleted key vaults (Key Vaults blade, "Managed deleted vaults", then select current subscription).  This error usually is presented when there is a key vault of the same name in soft delete state.  If you run the blueprint, then delete it and go to run it again, as might be the case in dev and/or test, this could happen.

The best way to avoid this is using the script 'Remove-AzAvdBpDeployment.ps1' and specify the parameter 'PurgeKeyVault'.  Then the previous key vault is soft deleted, and purged.  Then you shouldn't encounter this problem.

Thanks,

Robert Smith

**Comment by jlou07** [comment]
Hi Robert,

It worked thanks :)
We also have to be careful the the length of the rg prefix :
The artifact 'keyvault' of type 'Template' failed to deploy due to the following error: Template deployment failed with error [ { "code": "VaultNameNotValid", "message": "The vault name 'AVDBP01jlo2-sharedsvcs-kv' is invalid. A vault's name must be between 3-24 alphanumeric characters. 

Thanks,

Jean-Loup

**Comment by jlou07** [comment]
Hi Robert,

Today I launched the blueprint on a new Azure subscription.
As you can see below, I still have my error message about my key vault.

The error message is talking about name globally unique 
"The vault name 'AVDBP01-sharedsvcs-kv' is already in use. Vault names are globally unique, so it is possible that the name is already taken. "

That name "AVDBP01-sharedsvcs-kv" is the default name given by the script, don't you think we need to randomize it ?

Jean-Loup

![vault](https://user-images.githubusercontent.com/58774660/136094766-8711e240-6d14-44eb-9961-2e742bdf1c37.png)

**Comment by robsmi-msfte** [comment]
Hello Jean-Loup,

I wasn't explicitly aware that the key vault name had to be unique, presumably in the entire cloud.  As I research it, it looks like a storage account which has the same constraints.

I would recommend changing the resource prefix from the default.  I am editing the example parameters file, and also putting some extra verbiage in the Readme.md for this issue.

I'm sorry that you're still running into trouble.  But if you hang in there, change that prefix name to some unique 8 character string, I believe you will have success.

Thanks,

Robert Smith
