### ISSUE TITLE
Use Active Directory Domain controllers.

### ISSUE THREAD

**Issue by Takescake** [Azure/AVDBlueprint#129]
Hello,

I was wondering if anyone has looked into using this with an existing domain that maybe you have a VPN build too where it could spin up two AD DS servers not using the azure turn key solution. 

If there is I'd love to check out the documentation or if not I'll get to editing on my own!

Thanks for this great repo.

**Comment by robsmi-msfte** [comment]
Hello @Takescake,

We have not gotten that far with this solution yet.  We have instructions on how to integrate with an existing domain if there is one.  We appreciate the feedback and will consider it for a future iteration of the Blueprint.

Thanks,

Robert Smith
