### ISSUE TITLE
Maybe a short sleep between creation of the User Managed identity and Global Admin assignment.

### ISSUE THREAD

**Issue by chrismrutledge** [Azure/AVDBlueprint#131]
First run through I received this error:
Assigning Azure AD role 'Global Administrator' to the managed identity
Get-AzureADMSRoleAssignment : Error occurred while executing GetAzureADMSRoleAssignments 
Code: Request_ResourceNotFound

Throwing a 10 second sleep in the script will probably fix the issue. After creating the managed identity it seems to take a few seconds to actually show up.  Second run through, no issues.

**Comment by chrismrutledge** [comment]
> Hello @chrismrutledge ,
> 
> We have encountered this problem a few times and agree with your assessment. What I have been testing just today, is a "Do Until" loop that uses 'Get-AzUserAssignedIdentity' and waits for it to return a result. I decided to do it that way, because sometimes even 3 seconds of pause isn't enough.
> 
> We appreciate the feedback and will get this incorporated in to the main branch soon.
> 
> Thanks,
> 
> Robert Smith

Completely concur, that's a much better way of dealing with the delay.

**Comment by robsmi-msfte** [comment]
Nothing new since October, so closing issue.  If there is still a problem please open a new issue.
