### ISSUE TITLE
Error in Azure China

### ISSUE THREAD

**Issue by cengxiye** [Azure/AVDBlueprint#135]
Hi Team,

I tried this Blueprint in Azure China, but have below errors.

![image](https://user-images.githubusercontent.com/30278877/138250572-84c6d14b-a625-44d3-b6a6-86d852a38367.png)
![image](https://user-images.githubusercontent.com/30278877/138250606-d7f26220-d4d9-4385-82fc-499b03e2f54f.png)
![image](https://user-images.githubusercontent.com/30278877/138250649-f060327b-0b0d-4025-a0b1-2fd4aa32e20d.png)

Any clues where I should troubleshoot?

**Comment by robsmi-msfte** [comment]
We rewrote code that is run during UAI creation and role assignment, specifically to address the issues above.  If you still have issues running the script, please open a new issue.  Thank you.
