### ISSUE TITLE
Provide an architecture diagram of the solution

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/AVDBlueprint#141]
Having a visual (architecture diagram) of what the blueprint deploys would be useful. For example, visually indicating the relationship between the test user(s) and Key Vaults would be great.

**Comment by robsmi-msfte** [comment]
Hello @SvenAelterman ,

I have a very basic diagram of what the Blueprint does today.  It is based on the dependency flow of the artifacts, as they are without modification of the "DependsOn" values.  Let us know if you need something more than this.

Thanks,

Robert Smith

[AVD_BluePrint_FD_ArtifactFlow.pdf](https://github.com/Azure/AVDBlueprint/files/7839965/AVD_BluePrint_FD_ArtifactFlow.pdf)
