### ISSUE TITLE
Deployment using this blueprint no longer works

### ISSUE THREAD

**Issue by cf5joe** [Azure/AVDBlueprint#78]
Has anyone else tried deploying this blueprint recently?  Its not working any longer.  I'm assuming the underlying parameter requirements have changed slightly as I'm getting errors.  I worked through the first roadblock, honestly don't remember what the problem was.  Now I'm facing a second issue with "accessPolicies" in the KeyVault artifact.  I found a stackoverflow article that mentioned that "all" is no longer supported for some of these parameter values.  https://stackoverflow.com/questions/55245815/arm-template-keyvault-accesspolicies-inside-object-parameter

Moving past the keyvault issues, the next series of issues appears to be with the deploymentID, the blueprint requires a value for this but it took me forever to figure out what it wanted.  It would be nice if this was dynamically generated somehow or at least a better description of what is required here.  

I'm still fighting my way through it, but this is definitely not a download and deploy template anymore.

**Comment by robsmi-msfte** [comment]
Hello @cf5joe,

Regarding the first issue, we have not changed the KeyVault code in a long time.  We have made a lot of other changes, but we always test many times.  We have not had any indication that "all" is no longer supported.

Could you reply with a log example of the error (with your specific data removed)?

For DeploymentID, that is generated during Blueprint assignment as a new GUID.  The default value is in the "avdDeploy.json":

"defaultValue": "[newGuid()]"

Thanks,

Robert Smith

**Comment by dennispayne** [comment]
Closing issue as it mentions multiple topics. Please feel free to open new issues for each item so they may be picked up in future development. Thanks!
